---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transacoes
  labels:
    app: transacoes
spec:
  selector:
    matchLabels:
      app: transacoes
  replicas: 1
  template:
    metadata:
      labels:
        app: transacoes
    spec:
      containers:
      - name: transacoes
        image: marcos/transacoes:latest
        ports:
        - name: debug
          containerPort: 9005
        - name: application
          containerPort: 8080
        env:
        - name: SPRING_PROFILE
          value: "local"
        - name: DB_HOST
          value: "mongo"
        - name: DB_PORT
          value: "27017"
        - name: DB_NAME
          value: "transacoes"
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          value: "rootpassword"
        - name: DEBUG_PORT
          value: "9005"
---
apiVersion: v1
kind: Service
metadata:
  name: transacoes
spec:
  selector:
    app: transacoes
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30036
    protocol: TCP
  - name: debug
    port: 9005
    targetPort: 9005
    nodePort: 30037
    protocol: TCP