---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
    chart: mongo
    release: mongo
    heritage: mongo
spec:
  selector:
    matchLabels:
      app: mongo
      release: mongo
  template:
    metadata:
      labels:
        app: mongo
        release: mongo
        chart: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:3.6.21-xenial
          imagePullPolicy: Always
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: root
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: rootpassword
          - name: MONGODB_ROOT_PASSWORD
            value: rootpassword
          - name: MONGODB_USERNAME
            value: mongouser
          - name: MONGODB_PASSWORD
            value: mongouser
          - name: MONGODB_DATABASE
            value: mongodatabase
          - name: MONGODB_ENABLE_DIRECTORY_PER_DB
            value: "no"
          ports:
            - name: mongodb
              containerPort: 27017
          livenessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: NodePort
  selector:
    app: mongo
  ports:
    - name: mongoport
      port: 27017
      targetPort: 27017
      nodePort: 30017
      protocol: TCP